Repository RedHatQE/widgetastic.core, pull requests merged in 2019-05, with the labels that each got.

#153 [RFR ] py37 check travis
  .travis.yml
  setup.py
  tox.ini
Labels: enhancement

#101 [1LP][RFR] IFrame View
  docs/advanced_usage.rst
  setup.py
  src/widgetastic/browser.py
  src/widgetastic/widget/base.py
  testing/conftest.py
  testing/html/iframe_page.html
  testing/html/iframe_page2.html
  testing/html/testing_page.html
  testing/test_view.py
  tox.ini
Labels: enhancement, tech-debt

#154 changed travis push account to my own
  .travis.yml
Labels: bug
