Repository RedHatQE/widgetastic.core, pull requests merged in 2020-09, with the labels that each got.

#174 RFR: switch_to_alert call deprecation
  src/widgetastic/browser.py
  src/widgetastic/widget/base.py
  testing/html/testing_page.html
  testing/test_browser.py
Labels: tech-debt

#170 [RFR] Reset table tree if table element changes
  src/widgetastic/widget/table.py
Labels: bug

#175 RFR: save screenshot method
  src/widgetastic/browser.py
  testing/test_browser.py
Labels: enhancement
